apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None  # Permite una conexión interna estable a través de su nombre DNS
  selector:
    app: mysql
