apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany # Debe coincidir con el modo de acceso del PV
  resources:
    requests:
      storage: 5Gi # Debe ser igual o menor que la capacidad del PV
  storageClassName: efs-sc # Debe coincidir con el Storage Class del PV
