apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc-last
spec:
  storageClassName: efs-sc  # Debe coincidir con el PV
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: drupal-pv-last

