apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv-last
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc  # Agrega la StorageClass aquí
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02de4118e833fb51d  # Incluye el Access Point ID aquí

