apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 2  # Alta disponibilidad con 2 réplicas
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:latest
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: "mysql-0.mysql"  # Ajuste según el nombre de tu servicio MySQL
        - name: MYSQL_DATABASE
          value: "drupal"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "dragonball2004"

