apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Este tamaño no es crítico ya que EFS se ajusta automáticamente
  storageClassName: efs-sc

